### ISSUE TITLE
Ensure app accessility/usability

### ISSUE THREAD

**Issue by michaelhaaf** [Carlos-LX/5A6-group-project#40]
---
title: Ensure app accessility/usability
milestone: Milestone 4b Requirements
label: enhancement
---

## Requirements
- A core requirement is for your app to be usable. You should actually try using your app on a mobile phone and keeping track of any improvements you make to the usability (device rotation, typing, clicking buttons, navigating, etc.)
- You should use the techniques learned in Assignment 4 and ensure your entire app adheres to basic accesibility standards (color contrast, button size, semantics, etc.)

## Priority
You can leave this task for last, but make sure it is done before the deadline.

## Resources

- See Assignment 4 codelab
- You will have to do some independent research to solve the usability problems you may encounter in your application. Remember that the course notes have a lot of resources to start with especialyl re: state management/UI/etc.

## Before completing this ticket:

- [x] Entire codebase has been gone over for these kind of issues/improvements
- [x] All usability improvements you make are linked/documented here

**Comment by Carlos-LX** [comment]
Visuals:
- Overhauled the light theme in order to make elements easier to read
- Increased the size of icons by encasing them within IconButton.
- Changed the text color of elements that were hard to read in the Dark Theme
- Changed contrasts of elements 
- Added a label for each NavigationBarItem
Usability:
- Changed navigation so that it uses LocalNavController and prevents a navhost to be passed to a child.
- Changed both the favorites and library composable in order to expand a book when any part of the card is clicked, not just the book item.
- Removed the fontSize slider
- Overhaul of sign up and sign in screens
- Added a new starting page to allow the user to sign in
- Added a focus manager so that the focus moves to the next text field when user presses enter (or calls the sign up/sign in function)
- Switched some navigateSingleTopTo functions with navigate in order to allow the user to go back when clicking on a book's details.
